### ISSUE TITLE
One more requirement

### ISSUE THREAD

**Issue by Kumappus** [VictorNicollet/Ohm#2]
Package json-static is missing.
"sudo apt-get install libjson-static-camlp4-dev"
is also required.

**Comment by VictorNicollet** [comment]
This shouldn't be the case (neither json-static nor json-wheel should be dependencies). I will check for lingering dependencies.

**Comment by VictorNicollet** [comment]
Fixed in the [latest commit](https://github.com/VictorNicollet/Ohm/commit/a5e0b0108abff3290c3eb31d545c1d8b4e2571dd). Thank you for mentioning this !
